tools/dockerfiles/geep-Dockerfile, tools/geep.cwl, workflows/chipseq-pe.cwl, workflows/chipseq-se.cwl, workflows/trim-chipseq-pe.cwl, workflows/trim-chipseq-se.cwl
=> Update GEEP to v0.0.4

.travis.yml, tests/conformance_tests.yaml, tests/super-enhancer-1.json, tests/super-enhancer-2.json, tests/super-enhancer-3.json, tools/makegff.cwl
Update travis configuration with
- schema-salad==3.0.20181206233650
=> Fixed tests

tools/dockerfiles/manorm-Dockerfile, tools/dockerfiles/scripts/manorm.R, tools/dockerfiles/scripts/run_manorm.sh, workflows/manorm.cwl
metadata in progress
TODO: integrate iaintersect
=> Add manorm.cwl. Only functional part

workflows/bismark-indices.cwl, workflows/chipseq-pe.cwl, workflows/chipseq-se.cwl, workflows/trim-atacseq-pe.cwl, workflows/trim-atacseq-se.cwl, workflows/trim-chipseq-pe.cwl, workflows/trim-chipseq-se.cwl
Set input as a folder with the FASTA files
=> Simplify Bismark Prepare Indices pipeline

workflows/chipseq-pe.cwl, workflows/chipseq-se.cwl, workflows/trim-atacseq-pe.cwl, workflows/trim-atacseq-se.cwl, workflows/trim-chipseq-pe.cwl, workflows/trim-chipseq-se.cwl
=> Update Preseq extrapolation range to 1G reads

tests/conformance_tests.yaml, tools/deseq-advanced.cwl, tools/dockerfiles/scidap-deseq-Dockerfile, tools/dockerfiles/scripts/run_deseq.R, workflows/deseq.cwl
Use -log10(padj) for scatterplot
=> Update DESeq tool and pipeline

workflows/chipseq-pe.cwl, workflows/chipseq-se.cwl, workflows/rnaseq-pe-dutp-mitochondrial.cwl, workflows/rnaseq-pe-dutp.cwl, workflows/rnaseq-pe.cwl, workflows/rnaseq-se-dutp-mitochondrial.cwl, workflows/rnaseq-se-dutp.cwl, workflows/rnaseq-se.cwl, workflows/trim-atacseq-pe.cwl, workflows/trim-atacseq-se.cwl, workflows/trim-chipseq-pe.cwl, workflows/trim-chipseq-se.cwl, workflows/trim-rnaseq-pe-dutp.cwl, workflows/trim-rnaseq-pe.cwl, workflows/trim-rnaseq-se-dutp.cwl, workflows/trim-rnaseq-se.cwl
Add visualization for the following outputs of ChIP/ATAC - Seq:
- iaintersect_result
- macs2_narrow_peaks
- macs2_broad_peaks
- macs2_gapped_peak
Add visualization for rpkm_genes output of RNA-Seq
=> Update visualization for ChIP/ATAC/RNA - seq pipelines

workflows/chipseq-se.cwl
=> Preseq Marker visualization test

workflows/bismark-methylation-se.cwl
Outputs BAM file, add samtools sort index
step. Add visualization for BAM and BED files
=> Update Bismark Methylation Pipeline

workflows/bismark-methylation-se.cwl
=> Replace Trimmomatic with Trimgalow in Methylation pipeline

workflows/bismark-methylation-se.cwl
There isn't any threads input in bismark_extract_methylation
step
=> Fix bug in Bismark Methylation pipeline

tests/conformance_tests.yaml, tests/genome-indices-1.json, tools/samtools-faidx.cwl, tools/ucsc-twobit-to-fa.cwl, workflows/genome-indices.cwl
Workflow outputs the following files for IGV
- refgene.bed
- refgene.bed.tbi
- fa
- fa.fai
- cytoBand.txt
=> Update genome-indices to produce data for IGV

tests/conformance_tests.yaml, tools/dockerfiles/ucscuserapps-Dockerfile, tools/ucsc-twobit-to-fa.cwl, workflows/genome-indices.cwl
Not tested. Should be tested with the real data.
TODO: make mitochondrial_annotation_tab optional
=> Update genome-indices to support fasta, gz, 2bit

workflows/rnaseq-pe-dutp-mitochondrial.cwl, workflows/rnaseq-pe-dutp.cwl, workflows/rnaseq-se-dutp-mitochondrial.cwl, workflows/rnaseq-se-dutp.cwl, workflows/trim-quantseq-mrnaseq-se-strand-specific.cwl, workflows/trim-rnaseq-pe-dutp.cwl, workflows/trim-rnaseq-pe-smarter-dutp.cwl, workflows/trim-rnaseq-se-dutp.cwl
https://datirium.atlassian.net/browse/SDAP-786
=> changed bigwig names for IGV

tools/gseapy.cwl, workflows/gseapy.cwl
- updated to the latest MSigDB 2022.1.Hs release
- added new genesets
* KEGG_2021_Human
* Reactome_2022
* WikiPathways_2019_Human
=> Update GSEA with the latest MSigDB version, add new genesets

dockerfiles/scidap-deseq-Dockerfile, dockerfiles/scripts/run_deseq.R, tests/gseapy-4.json, tools/deseq-advanced.cwl, tools/gseapy.cwl, workflows/deseq.cwl, workflows/diffbind-multi-factor.cwl, workflows/gseapy.cwl
updated deseq dockerfile to output all and filtered (by padj) count table for GSEA and morpheus heatmap, respectively.
=> Sdap 1095 deseq count table fix for gsea

tools/preseq-plot-data.cwl, tools/samtools-clean-headers.cwl, workflows/cutandrun-seacr-pe.cwl, workflows/filter-diffbind-for-heatmap.cwl
removed headers from stringent and relaxed peak files
force `.bed` extension as well for IGV
=> SDAP-1123 cutandrun seacr bed file updates

tools/vc-germline-pe.cwl, workflows/vc-germline-pe.cwl
Added vcf extension explicitly to output names of VCF files.
=> SDAP-1045 vcf extensions

tools/deseq-multi-factor.cwl, workflows/deseq-multi-factor.cwl, workflows/filter-deseq-for-heatmap.cwl
Uses Combat-Seq instead of Limma
=> Update DESeq2 workflow to use Combat-Seq for batch effect removal

dockerfiles/scripts/run_genelists.sh, dockerfiles/scripts/run_genelists_heatmap.R, tools/genelists-deseq-diffbind.cwl, tools/genelists-sets.cwl, workflows/filter-deseq-for-heatmap.cwl, workflows/filter-diffbind-for-heatmap.cwl, workflows/genelists-deseq-diffbind.cwl, workflows/genelists-sets.cwl
set operation workflow and associated tool for overlapping filtered genelists
includes updates for upstreams and other minor edits
=> Sdap 1167 setops

dockerfiles/scidap-genelists-Dockerfile, dockerfiles/scripts/run_genelists.sh, dockerfiles/scripts/run_genelists_heatmap.R, dockerfiles/scripts/run_qiime2_aggregate.sh, dockerfiles/scripts/run_qiime2_sample_pe.sh, tools/genelists-deseq-diffbind.cwl, workflows/genelists-deseq-diffbind.cwl
also includes minor changes to qiime scripts
=> SDAP-1192 genelist heatmap updates

dockerfiles/scidap-bedops-Dockerfile, tools/filter-peaks-by-overlap.cwl, workflows/cutandrun-macs2-pe.cwl, workflows/diffbind-multi-factor.cwl, workflows/diffbind.cwl, workflows/filter-peaks-by-overlap.cwl, workflows/filter-peaks-for-heatmap.cwl, workflows/genelists-sets.cwl, workflows/trim-atacseq-pe.cwl, workflows/trim-atacseq-se.cwl, workflows/trim-chipseq-pe.cwl, workflows/trim-chipseq-se.cwl
PR also includes:
- iaintersect output updates to diffbind and diffbind mf workflows for compatibility
- peak bed files in igv for peak filter for heatmap workflow
- renamed outputs in genelist-setops workflow for compatibility
- updated control file description for atac/chip/c&r workflows
=> SDAP-1186 setops for peak overlaps

dockerfiles/scidap-deseqspikein-Dockerfile, dockerfiles/scidap-erccnorm-Dockerfile, dockerfiles/scripts/run_deseq_for_spikein.R, dockerfiles/scripts/run_ercc_norm.sh, dockerfiles/scripts/run_ercc_regression.R, tools/deseq-advanced-for-spikein.cwl, tools/ercc-norm.cwl, tools/gseapy-reportsummary.cwl, workflows/deseq-for-spikein.cwl, workflows/filter-deseq-for-heatmap.cwl, workflows/gseapy.cwl, workflows/trim-rnaseq-pe-ercc.cwl
Primary additions are the ERCC spike-in normalization RNA-Seq PE workflow, and a new DESeq workflow that disables library size normalization (intended to be used with the ERCC spike-in normalized samples).
Other workflow/tool/script changes are generally minor, either small updates to overview files or workflow descriptions.
=> SDAP-1197-1199 ercc spikein norm and de workflows

dockerfiles/scripts/run_ercc_regression.R, workflows/gseapy.cwl, workflows/trim-rnaseq-pe-ercc.cwl
add unscaled gene expression table as an additional tab in the sample output
force scaled total reads to integer for DESeq2 analysis
add deseq-spikein workflow as upstream to GSEA workflow
=> SDAP-1212 updates to ercc and gseapy

workflows/filter-peaks-for-heatmap.cwl, workflows/genelists-deseq-diffbind.cwl, workflows/homer-motif-analysis-bg.cwl, workflows/homer-motif-analysis.cwl
fixed individual sample filter peaks workflow output, for compatibility
added it as upstream for motif (random & custom) and genelist heatmap workflows
=> SDAP-1216 filter peaks PR redo

tools/deseq-multi-factor.cwl, tools/diffbind-multi-factor.cwl, tools/diffbind.cwl, tools/files-to-folder.cwl, tools/umi-tools-dedup.cwl, workflows/deseq-multi-factor.cwl, workflows/diffbind-multi-factor.cwl, workflows/diffbind.cwl, workflows/trim-quantseq-mrnaseq-se-strand-specific.cwl, workflows/trim-quantseq-mrnaseq-se.cwl, workflows/trim-rnaseq-pe-dutp.cwl, workflows/trim-rnaseq-pe-smarter-dutp.cwl, workflows/trim-rnaseq-pe.cwl, workflows/trim-rnaseq-se-dutp.cwl, workflows/trim-rnaseq-se.cwl
Reverts datirium/workflows#179
=> Revert "Pr 1 not sc updates"

tools/deseq-advanced.cwl, workflows/cutandrun-macs2-pe.cwl, workflows/cutandrun-seacr-pe.cwl, workflows/deseq.cwl, workflows/manorm2.cwl
contains valerii's deseq updates
minor change to manorm2 (adding cutandrun workflows as upstreams)
output name change in cutandrun workflows for filtering workflow compatibility
=> valeriis deseq update for db changes and minor cutandrun manorm2 updates

dockerfiles/scidap-tgif-Dockerfile, tools/tgif-ncats.cwl, tools/tgif-primer3.cwl, tools/tgif-summary.cwl, workflows/tgif.cwl
new workflow, TgIF - Transgene Insertion Finder
=> SDAP-1252 tgif workflow

dockerfiles/kraken2-Dockerfile, dockerfiles/scidap-metaphlan-Dockerfile, tools/bypass-trimgalore-pe.cwl, tools/bypass-trimgalore-se.cwl, tools/extract-fastq.cwl, tools/fastq-dump.cwl, tools/fastx-quality-stats.cwl, tools/k2-classify-pe.cwl, tools/k2-download-db.cwl, tools/rename.cwl, tools/trimgalore.cwl, tools/wgs-humann-pe.cwl, tools/wgs-kneaddata-pe.cwl, tools/wgs-metaphlan-pe.cwl, workflows/kraken2-classify-pe.cwl, workflows/kraken2-databases.cwl, workflows/wgs-metagenomics-pe.cwl
wgs workflow for single metagenomic sample
uses kneaddata, kraken2, metaphlan, and humann
includes resource req in all associated tools
=> SDAP-1247 wgs metagenomic sample workflow
